title: GitHub Learning
description: Documenting the journey of learning to use GitHub and related tools
theme: minima
baseurl: "/github-learning"
url: "https://ljxme.github.io"
future: true
timezone: Asia/Shanghai

plugins:
  - jekyll-feed
